#!/bin/bash

Target=${1}
RegionID="us-east-1"

if [[ ${Target} =~ "rogers" ]]; then
    RegionID="ca-central-1"
fi
if [[ ${Target} =~ "sielvizion" ]]; then
    RegionID="ap-south-1"
fi
if [[ ${Target} =~ "sbaintl" ]]; then
    RegionID="sa-east-1"
fi

InstanceID="$(aws ec2 describe-instances --region ${RegionID} --filters "Name=tag:Name,Values=${Target}" --query 'Reservations[*].Instances[*].[InstanceId]' --output text)"

sftp -o ProxyCommand="aws ssm start-session --target ${InstanceID} --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --region ${RegionID}" ec2-user@${Target}
