#!/bin/bash
trap 'pkill -f "caffeinate -d"' EXIT
caffeinate -d &
while true;
do
    osascript -e 'tell application "Microsoft Teams" to activate'
    osascript -e 'tell application "System Events" to keystroke "2" using {command down}'
    osascript -e 'tell application "Mail" to activate'
    echo "Teams Status Refreshed - $(date)"
    sleep $(($RANDOM%(330-250+1)+250))
done