#!/bin/bash
trap 'pkill -f "caffeinate -d"' EXIT
caffeinate -d &
while true;
do
    osascript -e 'tell application "Microsoft Teams" to activate'
    osascript -e 'tell application "System Events" to keystroke "2" using {command down}'
    echo "Teams Status Refreshed - $(date)"
    sleep $(($RANDOM%(600-300+1)+300))
done